/**
 * Populates the AppSheet RFQ sheet from the Data List.
 *
 * Current extraction scope:
 * - PROCUREMENT METHOD = (RA 12009) Section 34: Small Value Procurement
 * - STATUS is blank or Active
 * - POSTING DATE has arrived (<= today)
 *   OR SUBMISSION OF BIDS has not yet passed (>= today)
 *
 * One RFQ row is created for each qualifying Data List row.
 * RFQ_ID is generated by this script and remains attached to the
 * extracted row on subsequent runs.
 *
 * RFQ_STATUS is automatically set to Active or Closed for new records.
 * Existing Secretariat-controlled statuses are preserved.
 */
function populateRFQ() {
  const sourceSpreadsheetId = '1xb76Hf1uV600UyCIuev1iBupolLWR9V2KVx9FffK3SU';
  const sourceSheetName = 'Data List';

  const targetSpreadsheetId = '1VCryDviOFJzdNEYiVuWo76Q-uB4oOrJXrBMxLylsmzU';
  const targetSheetName = 'RFQ';

  const requiredProcurementMethod = '(RA 12009) Section 34: Small Value Procurement';
  const today = startOfDay_(new Date());

  const sourceSS = SpreadsheetApp.openById(sourceSpreadsheetId);
  const targetSS = SpreadsheetApp.openById(targetSpreadsheetId);
  const sourceSheet = sourceSS.getSheetByName(sourceSheetName);
  const targetSheet = targetSS.getSheetByName(targetSheetName);

  if (!sourceSheet) throw new Error(`Source sheet "${sourceSheetName}" not found.`);
  if (!targetSheet) throw new Error(`Target sheet "${targetSheetName}" not found.`);

  const sourceData = sourceSheet.getDataRange().getValues();
  const targetData = targetSheet.getDataRange().getValues();

  if (sourceData.length === 0) throw new Error('Data List is empty.');
  if (targetData.length === 0) throw new Error('RFQ sheet must have a header row.');

  const sourceHeaders = sourceData[0].map(h => String(h).trim());
  const targetHeaders = targetData[0].map(h => String(h).trim());

  const sourceIndex = buildHeaderIndex_(sourceHeaders);
  const targetIndex = buildHeaderIndex_(targetHeaders);

  const requiredSourceColumns = [
    'ITEM DESCRIPTION',
    'CATEGORY',
    'END-USER',
    'PR DATE',
    'PR NO.',
    'PR QUANTITY',
    'PR ABC',
    'PR TOTAL ABC',
    'POSTING DATE',
    'PHILGEPS REFERENCE NO.',
    'PROJECT ID',
    'SUBMISSION OF BIDS',
    'PROCUREMENT METHOD',
    'STATUS',
    'PROJECT TITLE'
  ];

  const requiredTargetColumns = [
    'RFQ_ID',
    'BID NO.',
    'RFQ_TITLE',
    'ITEM DESCRIPTION',
    'CATEGORY',
    'END_USER',
    'PR DATE',
    'PR NO.',
    'PR QUANTITY',
    'PR ABC',
    'PR TOTAL ABC',
    'POSTING_DATE',
    'PHILGEPS_REFERENCE_NO.',
    'SUBMISSION_DATE',
    'RFQ_STATUS',
    'CANCELLATION_REASON',
    'RFQ_FILES'
  ];

  const missingSource = requiredSourceColumns.filter(name => sourceIndex[name] === undefined);
  const missingTarget = requiredTargetColumns.filter(name => targetIndex[name] === undefined);

  if (missingSource.length) {
    throw new Error(`Missing source columns: ${missingSource.join(', ')}`);
  }
  if (missingTarget.length) {
    throw new Error(`Missing RFQ columns: ${missingTarget.join(', ')}`);
  }

  // Existing RFQ records are indexed by a stable source signature.
  // The signature prevents duplicate RFQ_IDs when this function runs again.
  const existingRecords = new Map();
  let nextIdNumber = 1;

  for (let r = 1; r < targetData.length; r++) {
    const row = targetData[r];
    const rfqId = String(row[targetIndex.RFQ_ID] || '').trim();
    const bidNo = String(row[targetIndex['BID NO.']] || '').trim();
    const itemDescription = String(row[targetIndex['ITEM DESCRIPTION']] || '').trim();
    const prNo = String(row[targetIndex['PR NO.']] || '').trim();

    if (rfqId) {
      const match = rfqId.match(/RFQ-(\d+)/i);
      if (match) nextIdNumber = Math.max(nextIdNumber, Number(match[1]) + 1);
    }

    if (bidNo || itemDescription || prNo) {
      existingRecords.set(makeRFQSignature_(bidNo, itemDescription, prNo), {
        rowNumber: r + 1,
        rfqId: rfqId,
        status: String(row[targetIndex.RFQ_STATUS] || '').trim()
      });
    }
  }

  const rowsToAppend = [];
  const rowsToUpdate = [];
  let added = 0;
  let updated = 0;
  let skipped = 0;

  for (let r = 1; r < sourceData.length; r++) {
    const sourceRow = sourceData[r];

    const procurementMethod = String(sourceRow[sourceIndex['PROCUREMENT METHOD']] || '').trim();
    if (procurementMethod !== requiredProcurementMethod) {
      skipped++;
      continue;
    }

    const sourceStatus = String(sourceRow[sourceIndex.STATUS] || '').trim();
    if (sourceStatus !== '' && sourceStatus !== 'Active') {
      skipped++;
      continue;
    }

    const bidNo = extractBetweenParentheses_(sourceRow[sourceIndex['PROJECT ID']]);
    const projectTitle = sourceRow[sourceIndex['PROJECT TITLE']];
    const itemDescription = sourceRow[sourceIndex['ITEM DESCRIPTION']];
    const postingDate = parseRFQDate_(sourceRow[sourceIndex['POSTING DATE']]);
    const submissionDate = parseRFQDate_(sourceRow[sourceIndex['SUBMISSION OF BIDS']]);

    // For the initial population, the record must already be posted OR
    // still have a submission date in the future/today.
    const postingHasArrived = postingDate && postingDate <= today;
    const submissionHasNotPassed = submissionDate && submissionDate >= today;
    if (!postingHasArrived && !submissionHasNotPassed) {
      skipped++;
      continue;
    }

    if (!bidNo || !projectTitle || !itemDescription || !postingDate || !submissionDate) {
      skipped++;
      continue;
    }

    const signature = makeRFQSignature_(bidNo, itemDescription, sourceRow[sourceIndex['PR NO.']]);
    const existing = existingRecords.get(signature);

    if (existing) {
      // Update source-derived fields but preserve RFQ_STATUS, CANCELLATION_REASON,
      // and RFQ_FILES because those belong to the RFQ workflow/Secretariat.
      const rowNumber = existing.rowNumber;
      const currentRow = targetSheet.getRange(rowNumber, 1, 1, targetHeaders.length).getValues()[0];

      setTargetValue_(currentRow, targetIndex['BID NO.'], bidNo);
      setTargetValue_(currentRow, targetIndex.RFQ_TITLE, projectTitle);
      setTargetValue_(currentRow, targetIndex['ITEM DESCRIPTION'], itemDescription);
      setTargetValue_(currentRow, targetIndex.CATEGORY, sourceRow[sourceIndex.CATEGORY]);
      setTargetValue_(currentRow, targetIndex.END_USER, sourceRow[sourceIndex['END-USER']]);
      setTargetValue_(currentRow, targetIndex['PR DATE'], sourceRow[sourceIndex['PR DATE']]);
      setTargetValue_(currentRow, targetIndex['PR NO.'], sourceRow[sourceIndex['PR NO.']]);
      setTargetValue_(currentRow, targetIndex['PR QUANTITY'], sourceRow[sourceIndex['PR QUANTITY']]);
      setTargetValue_(currentRow, targetIndex['PR ABC'], sourceRow[sourceIndex['PR ABC']]);
      setTargetValue_(currentRow, targetIndex['PR TOTAL ABC'], sourceRow[sourceIndex['PR TOTAL ABC']]);
      setTargetValue_(currentRow, targetIndex.POSTING_DATE, postingDate);
      setTargetValue_(currentRow, targetIndex['PHILGEPS_REFERENCE_NO.'], sourceRow[sourceIndex['PHILGEPS REFERENCE NO.']]);
      setTargetValue_(currentRow, targetIndex.SUBMISSION_DATE, submissionDate);

      // Automatic status is refreshed only while the existing status is blank,
      // Active, or Closed. Other Secretariat decisions are preserved.
      const currentStatus = String(currentRow[targetIndex.RFQ_STATUS] || '').trim();
      if (currentStatus === '' || currentStatus === 'Active' || currentStatus === 'Closed') {
        currentRow[targetIndex.RFQ_STATUS] = submissionDate >= today ? 'Active' : 'Closed';
      }

      rowsToUpdate.push({ rowNumber, values: currentRow });
      updated++;
      continue;
    }

    const rfqId = `RFQ-${String(nextIdNumber++).padStart(6, '0')}`;
    const newRow = new Array(targetHeaders.length).fill('');

    newRow[targetIndex.RFQ_ID] = rfqId;
    newRow[targetIndex['BID NO.']] = bidNo;
    newRow[targetIndex.RFQ_TITLE] = projectTitle;
    newRow[targetIndex['ITEM DESCRIPTION']] = itemDescription;
    newRow[targetIndex.CATEGORY] = sourceRow[sourceIndex.CATEGORY];
    newRow[targetIndex.END_USER] = sourceRow[sourceIndex['END-USER']];
    newRow[targetIndex['PR DATE']] = sourceRow[sourceIndex['PR DATE']];
    newRow[targetIndex['PR NO.']] = sourceRow[sourceIndex['PR NO.']];
    newRow[targetIndex['PR QUANTITY']] = sourceRow[sourceIndex['PR QUANTITY']];
    newRow[targetIndex['PR ABC']] = sourceRow[sourceIndex['PR ABC']];
    newRow[targetIndex['PR TOTAL ABC']] = sourceRow[sourceIndex['PR TOTAL ABC']];
    newRow[targetIndex.POSTING_DATE] = postingDate;
    newRow[targetIndex['PHILGEPS_REFERENCE_NO.']] = sourceRow[sourceIndex['PHILGEPS REFERENCE NO.']];
    newRow[targetIndex.SUBMISSION_DATE] = submissionDate;
    newRow[targetIndex.RFQ_STATUS] = submissionDate >= today ? 'Active' : 'Closed';

    rowsToAppend.push(newRow);
    existingRecords.set(signature, { rowNumber: null, rfqId, status: newRow[targetIndex.RFQ_STATUS] });
    added++;
  }

  if (rowsToAppend.length) {
    targetSheet
      .getRange(targetSheet.getLastRow() + 1, 1, rowsToAppend.length, targetHeaders.length)
      .setValues(rowsToAppend);
  }

  for (const update of rowsToUpdate) {
    targetSheet
      .getRange(update.rowNumber, 1, 1, targetHeaders.length)
      .setValues([update.values]);
  }

  Logger.log(`RFQ population complete. Added: ${added}; Updated: ${updated}; Skipped: ${skipped}.`);
}

function buildHeaderIndex_(headers) {
  const index = {};
  headers.forEach((header, i) => {
    if (header) index[header] = i;
  });
  return index;
}

function setTargetValue_(row, index, value) {
  row[index] = value;
}

function makeRFQSignature_(bidNo, itemDescription, prNo) {
  return [bidNo, itemDescription, prNo]
    .map(value => String(value || '').trim().toUpperCase())
    .join('||');
}

function extractBetweenParentheses_(value) {
  if (!value) return '';
  const text = String(value).trim();
  const match = text.match(/\(([^)]+)\)/);
  return match ? match[1].trim() : text;
}

function parseRFQDate_(value) {
  if (!value) return null;

  if (Object.prototype.toString.call(value) === '[object Date]' && !isNaN(value.getTime())) {
    return new Date(value.getTime());
  }

  const parsed = new Date(value);
  return isNaN(parsed.getTime()) ? null : parsed;
}

function startOfDay_(date) {
  const result = new Date(date.getTime());
  result.setHours(0, 0, 0, 0);
  return result;
}
